services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: builder
    volumes:
      - frontend_dist:/app/dist
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - app-network

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:
  frontend_dist:

networks:
  app-network:
    driver: bridge
